/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects/$projectId/settings'
import { Route as ProjectsProjectIdNotificationsRouteImport } from './routes/projects/$projectId/notifications'
import { Route as ProjectsProjectIdKeysRouteImport } from './routes/projects/$projectId/keys'
import { Route as ProjectsProjectIdEmailsRouteImport } from './routes/projects/$projectId/emails'
import { Route as ProjectsProjectIdEntriesIndexRouteImport } from './routes/projects/$projectId/entries/index'
import { Route as ProjectsProjectIdEntriesEntryIdRouteImport } from './routes/projects/$projectId/entries/$entryId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdNotificationsRoute =
  ProjectsProjectIdNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdKeysRoute = ProjectsProjectIdKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdEmailsRoute = ProjectsProjectIdEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdEntriesIndexRoute =
  ProjectsProjectIdEntriesIndexRouteImport.update({
    id: '/entries/',
    path: '/entries/',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdEntriesEntryIdRoute =
  ProjectsProjectIdEntriesEntryIdRouteImport.update({
    id: '/entries/$entryId',
    path: '/entries/$entryId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/emails': typeof ProjectsProjectIdEmailsRoute
  '/projects/$projectId/keys': typeof ProjectsProjectIdKeysRoute
  '/projects/$projectId/notifications': typeof ProjectsProjectIdNotificationsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/entries/$entryId': typeof ProjectsProjectIdEntriesEntryIdRoute
  '/projects/$projectId/entries/': typeof ProjectsProjectIdEntriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/emails': typeof ProjectsProjectIdEmailsRoute
  '/projects/$projectId/keys': typeof ProjectsProjectIdKeysRoute
  '/projects/$projectId/notifications': typeof ProjectsProjectIdNotificationsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/entries/$entryId': typeof ProjectsProjectIdEntriesEntryIdRoute
  '/projects/$projectId/entries': typeof ProjectsProjectIdEntriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/emails': typeof ProjectsProjectIdEmailsRoute
  '/projects/$projectId/keys': typeof ProjectsProjectIdKeysRoute
  '/projects/$projectId/notifications': typeof ProjectsProjectIdNotificationsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/entries/$entryId': typeof ProjectsProjectIdEntriesEntryIdRoute
  '/projects/$projectId/entries/': typeof ProjectsProjectIdEntriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/settings'
    | '/signup'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/$projectId/emails'
    | '/projects/$projectId/keys'
    | '/projects/$projectId/notifications'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
    | '/projects/$projectId/entries/$entryId'
    | '/projects/$projectId/entries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/settings'
    | '/signup'
    | '/projects/new'
    | '/projects/$projectId/emails'
    | '/projects/$projectId/keys'
    | '/projects/$projectId/notifications'
    | '/projects/$projectId/settings'
    | '/projects/$projectId'
    | '/projects/$projectId/entries/$entryId'
    | '/projects/$projectId/entries'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/login'
    | '/settings'
    | '/signup'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/$projectId/emails'
    | '/projects/$projectId/keys'
    | '/projects/$projectId/notifications'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
    | '/projects/$projectId/entries/$entryId'
    | '/projects/$projectId/entries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/notifications': {
      id: '/projects/$projectId/notifications'
      path: '/notifications'
      fullPath: '/projects/$projectId/notifications'
      preLoaderRoute: typeof ProjectsProjectIdNotificationsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/keys': {
      id: '/projects/$projectId/keys'
      path: '/keys'
      fullPath: '/projects/$projectId/keys'
      preLoaderRoute: typeof ProjectsProjectIdKeysRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/emails': {
      id: '/projects/$projectId/emails'
      path: '/emails'
      fullPath: '/projects/$projectId/emails'
      preLoaderRoute: typeof ProjectsProjectIdEmailsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/entries/': {
      id: '/projects/$projectId/entries/'
      path: '/entries'
      fullPath: '/projects/$projectId/entries/'
      preLoaderRoute: typeof ProjectsProjectIdEntriesIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/entries/$entryId': {
      id: '/projects/$projectId/entries/$entryId'
      path: '/entries/$entryId'
      fullPath: '/projects/$projectId/entries/$entryId'
      preLoaderRoute: typeof ProjectsProjectIdEntriesEntryIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdEmailsRoute: typeof ProjectsProjectIdEmailsRoute
  ProjectsProjectIdKeysRoute: typeof ProjectsProjectIdKeysRoute
  ProjectsProjectIdNotificationsRoute: typeof ProjectsProjectIdNotificationsRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdEntriesEntryIdRoute: typeof ProjectsProjectIdEntriesEntryIdRoute
  ProjectsProjectIdEntriesIndexRoute: typeof ProjectsProjectIdEntriesIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdEmailsRoute: ProjectsProjectIdEmailsRoute,
  ProjectsProjectIdKeysRoute: ProjectsProjectIdKeysRoute,
  ProjectsProjectIdNotificationsRoute: ProjectsProjectIdNotificationsRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdEntriesEntryIdRoute: ProjectsProjectIdEntriesEntryIdRoute,
  ProjectsProjectIdEntriesIndexRoute: ProjectsProjectIdEntriesIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
