/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects/$projectId/settings'
import { Route as ProjectsProjectIdNotificationsRouteImport } from './routes/projects/$projectId/notifications'
import { Route as ProjectsProjectIdKeysRouteImport } from './routes/projects/$projectId/keys'
import { Route as ProjectsProjectIdEntriesRouteImport } from './routes/projects/$projectId/entries'
import { Route as ProjectsProjectIdEntriesEntryIdRouteImport } from './routes/projects/$projectId/entries/$entryId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdNotificationsRoute =
  ProjectsProjectIdNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdKeysRoute = ProjectsProjectIdKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdEntriesRoute =
  ProjectsProjectIdEntriesRouteImport.update({
    id: '/entries',
    path: '/entries',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdEntriesEntryIdRoute =
  ProjectsProjectIdEntriesEntryIdRouteImport.update({
    id: '/$entryId',
    path: '/$entryId',
    getParentRoute: () => ProjectsProjectIdEntriesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/entries': typeof ProjectsProjectIdEntriesRouteWithChildren
  '/projects/$projectId/keys': typeof ProjectsProjectIdKeysRoute
  '/projects/$projectId/notifications': typeof ProjectsProjectIdNotificationsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/entries/$entryId': typeof ProjectsProjectIdEntriesEntryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/entries': typeof ProjectsProjectIdEntriesRouteWithChildren
  '/projects/$projectId/keys': typeof ProjectsProjectIdKeysRoute
  '/projects/$projectId/notifications': typeof ProjectsProjectIdNotificationsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/entries/$entryId': typeof ProjectsProjectIdEntriesEntryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/entries': typeof ProjectsProjectIdEntriesRouteWithChildren
  '/projects/$projectId/keys': typeof ProjectsProjectIdKeysRoute
  '/projects/$projectId/notifications': typeof ProjectsProjectIdNotificationsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/entries/$entryId': typeof ProjectsProjectIdEntriesEntryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/$projectId/entries'
    | '/projects/$projectId/keys'
    | '/projects/$projectId/notifications'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
    | '/projects/$projectId/entries/$entryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/projects/new'
    | '/projects/$projectId/entries'
    | '/projects/$projectId/keys'
    | '/projects/$projectId/notifications'
    | '/projects/$projectId/settings'
    | '/projects/$projectId'
    | '/projects/$projectId/entries/$entryId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/$projectId/entries'
    | '/projects/$projectId/keys'
    | '/projects/$projectId/notifications'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
    | '/projects/$projectId/entries/$entryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/notifications': {
      id: '/projects/$projectId/notifications'
      path: '/notifications'
      fullPath: '/projects/$projectId/notifications'
      preLoaderRoute: typeof ProjectsProjectIdNotificationsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/keys': {
      id: '/projects/$projectId/keys'
      path: '/keys'
      fullPath: '/projects/$projectId/keys'
      preLoaderRoute: typeof ProjectsProjectIdKeysRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/entries': {
      id: '/projects/$projectId/entries'
      path: '/entries'
      fullPath: '/projects/$projectId/entries'
      preLoaderRoute: typeof ProjectsProjectIdEntriesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/entries/$entryId': {
      id: '/projects/$projectId/entries/$entryId'
      path: '/$entryId'
      fullPath: '/projects/$projectId/entries/$entryId'
      preLoaderRoute: typeof ProjectsProjectIdEntriesEntryIdRouteImport
      parentRoute: typeof ProjectsProjectIdEntriesRoute
    }
  }
}

interface ProjectsProjectIdEntriesRouteChildren {
  ProjectsProjectIdEntriesEntryIdRoute: typeof ProjectsProjectIdEntriesEntryIdRoute
}

const ProjectsProjectIdEntriesRouteChildren: ProjectsProjectIdEntriesRouteChildren =
  {
    ProjectsProjectIdEntriesEntryIdRoute: ProjectsProjectIdEntriesEntryIdRoute,
  }

const ProjectsProjectIdEntriesRouteWithChildren =
  ProjectsProjectIdEntriesRoute._addFileChildren(
    ProjectsProjectIdEntriesRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdEntriesRoute: typeof ProjectsProjectIdEntriesRouteWithChildren
  ProjectsProjectIdKeysRoute: typeof ProjectsProjectIdKeysRoute
  ProjectsProjectIdNotificationsRoute: typeof ProjectsProjectIdNotificationsRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdEntriesRoute: ProjectsProjectIdEntriesRouteWithChildren,
  ProjectsProjectIdKeysRoute: ProjectsProjectIdKeysRoute,
  ProjectsProjectIdNotificationsRoute: ProjectsProjectIdNotificationsRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
